# Project-wide Gradle settings.

# AndroidX package structure
android.useAndroidX=true

# Automatically convert third-party libraries to use AndroidX
android.enableJetifier=true

# Use non-transitive R classes
android.nonTransitiveRClass=false

# Kotlin code style
kotlin.code.style=official

# JVM Args
org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8
